[versions]
creative = "0.3.0-SNAPSHOT"
adventure = "4.9.3"
annotations = "23.0.0"

# reader-blockbench
gson = "2.8.0"

# runtime-minestom
minestom = "737b663a4c"


[libraries]
creative-api = { group = "team.unnamed", name = "creative-api", version.ref =  "creative" }
creative-server = { group = "team.unnamed", name = "creative-server", version.ref = "creative" }
adventure-api = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }

# reader-blockbench
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

# runtime-minestom
minestom = { group = "com.github.Minestom", name = "Minestom", version.ref = "minestom" }